[build-system]
build-backend = "hatchling.build"
requires = [
  "hatch-vcs",
  "hatchling",
]

[project]
name = "what-works-repo"
description = ""
requires-python = ">=3.13"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [
  "version",
]
dependencies = [
  "data-extraction-evaluation-toolkit",
  "dvc[ssh]>=3.67.1",
  "loguru>=0.7.3",
  "matplotlib>=3.11.2",
  "pyarrow>=25.0.1",
  "pydantic-settings>=2.14.2",
  "snakemake>=9.24",
  "snakemake-executor-plugin-slurm>=2.8",
  "typer>=0.27",
]
optional-dependencies.docs = [
  "mkdocs-material>=9.7.7",
]
optional-dependencies.ml = [
  "torch>=2.13",
  "transformers>=5.15",
]
optional-dependencies.nacsos = [
  "nacsos-data[scripts,utils]",
]

[dependency-groups]
dev = [
  "ruff>=0.16.4",
  "snakefmt>=2.0.3",
  "what-works-repo",
]

[tool.hatch]
version.source = "vcs"
build.targets.wheel.packages = [
  "src/what_works_repo",
]

[tool.uv]
sources.data-extraction-evaluation-toolkit = { git = "https://github.com/destiny-evidence/data-extraction-evaluation-toolkit.git", rev = "feature/%2317-train-test-splits" }
sources.nacsos_data = [
  { git = "git+https://gitlab.pik-potsdam.de/mcc-apsis/nacsos/nacsos-data.git", tag = "v0.24.53" },
]
sources.what_works_repo = { workspace = true, editable = true }
workspace.members = [
  ".",
]

[tool.ruff]
lint.select = [
  "B",
  "E",
  "F",
  "I",
  "UP",
  "W",
]

[tool.ty]
environment.python-version = "3.14"
